changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Features and Technical Overhaul
      labels:
        - enhancement
        - feature
    - title: Bug Fixes and Stability
      labels:
        - bug
        - fix
    - title: Testing and Validation
      labels:
        - testing
        - exhaustive-testing
    - title: Documentation and Standards
      labels:
        - documentation
        - docs
    - title: Maintenance and Housekeeping
      labels:
        - chore
        - build
        - ci
