pub const DEFAULT_RADIOS: &[(&str, &str, &str, &str)] = &[
    (
        "SomaFM Groove Salad",
        "http://ice1.somafm.com/groovesalad-128-mp3",
        "USA",
        "Ambient, Chillout",
    ),
    (
        "SomaFM Drone Zone",
        "http://ice1.somafm.com/dronezone-128-mp3",
        "USA",
        "Ambient, Space",
    ),
    (
        "FIP",
        "https://stream.radiofrance.fr/fip/fip_hifi.m3u8?id=radiofrance",
        "France",
        "Eclectic",
    ),
    (
        "Radio Paradise (Main)",
        "http://stream.radioparadise.com/mp3-128",
        "USA",
        "Rock, Eclectic",
    ),
    (
        "KEXP",
        "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
        "USA",
        "Alternative, Indie",
    ),
    (
        "NTS Radio 1",
        "https://stream-relay-geo.ntslive.net/stream",
        "UK",
        "Experimental",
    ),
    (
        "Antenne Bayern",
        "http://stream.antenne.de/antenne",
        "Germany",
        "Pop",
    ),
    (
        "Jazz24",
        "https://live.jazz24.org/jazz24-mp3",
        "USA",
        "Jazz",
    ),
    (
        "Cinemix",
        "http://94.23.252.14:8067/live",
        "France",
        "Soundtrack",
    ),
    (
        "Swiss Groove",
        "https://icecast.argon.ch/swissgroove",
        "Switzerland",
        "Groove, Funk",
    ),
    (
        "Radio 105",
        "http://shoutcast.radio105.it:8000/105.mp3",
        "Italy",
        "Pop",
    ),
    (
        "Classic FM",
        "http://stream.live.vc.bbc.co.uk/bbc_radio_three_offline",
        "UK",
        "Classical",
    ),
    (
        "Acid House",
        "http://abm22.com.au:8000/CONTAINER1",
        "Australia",
        "Electronic, Acid",
    ),
    (
        "Afro House",
        "http://abm22.com.au:8000/CONTAINER53",
        "Australia",
        "Electronic, Afro",
    ),
    (
        "KissFM",
        "http://online.kissfm.ua/KissFM",
        "Ukraine",
        "Electronic, Trance",
    ),
    (
        "Paddygrooves",
        "https://a12.siar.us/radio/8230/radio.mp3",
        "Bali",
        "Downtempo, Lounge",
    ),
    (
        "Funky Ass Tunes",
        "https://ams1.reliastream.com/proxy/john12/stream",
        "Ireland",
        "Funk, Soul",
    ),
    (
        "Abaco Libros y Cafe",
        "https://radio30.virtualtronics.com/proxy/abaco",
        "Colombia",
        "Jazz, Bossa Nova",
    ),
    (
        "Blues Revue",
        "http://live.str3am.com:2240/live",
        "USA",
        "Blues",
    ),
    (
        "Jazz & Blues Radio",
        "https://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3",
        "Switzerland",
        "Jazz, Blues",
    ),
    (
        "Jazz Eire",
        "https://visual.shoutca.st:8096/stream",
        "Ireland",
        "Jazz",
    ),
    (
        "Art Bell Radio",
        "http://stream.willstare.com:8450/",
        "USA",
        "Spoken Word, Paranormal",
    ),
    (
        "Roots FM",
        "http://138.201.198.218:8043/stream",
        "Germany",
        "Reggae, Dub",
    ),
    (
        "Double J",
        "http://live-radio01.mediahubaustralia.com/2jr/mp3/",
        "Australia",
        "Alternative",
    ),
    (
        "Svensk Folkmusik AkkA",
        "https://mediaserv38.live-streams.nl:8107/stream",
        "Sweden",
        "Folk",
    ),
    (
        "Ambient FM",
        "https://phoebe.streamerr.co:4140/ambient.mp3",
        "USA",
        "Ambient",
    ),
    (
        "Chillsky Chillhop",
        "https://chill.radioca.st/stream",
        "USA",
        "Lo-Fi, Hip Hop",
    ),
    (
        "Nature Radio",
        "https://nature-rex.radioca.st/stream",
        "Global",
        "Nature, Sounds",
    ),
    (
        "FreeCodeCamp Radio",
        "https://stream.freecodecamp.org/radio.mp3",
        "Global",
        "Lo-Fi, Focus",
    ),
    (
        "Robert Loglisci Radio",
        "https://radio.loglisci.com/listen/robertloglisciradio/radio.mp3",
        "Global",
        "Soundtrack",
    ),
    (
        "Cubic Space Radio",
        "http://music.cubicspace.fm:42424/mpeg",
        "Global",
        "Soul, Disco",
    ),
    (
        "Radio Regional Portugal",
        "http://193.70.40.92:8000/stream/2/",
        "Portugal",
        "News",
    ),
    (
        "Radio 100% Brasil",
        "http://193.70.40.92:8000/stream/11/",
        "Brazil",
        "Music",
    ),
    (
        "Da Hub Radio",
        "https://stream.dahubradio.co.uk:8848/stream",
        "UK",
        "Mixed",
    ),
    (
        "Voltaje Radio",
        "https://server5.mediasector.es:8070/voltaje",
        "Spain",
        "60s",
    ),
    (
        "La Diaria Radio",
        "https://radiolatina.live/8156/stream",
        "Global",
        "Misc",
    ),
    (
        "More Public Radio",
        "http://68.233.231.202:8107/stream",
        "Global",
        "Classic Jazz",
    ),
    (
        "Classic Hip Hop Radio",
        "http://73.191.71.239:8000/;",
        "Global",
        "Hip Hop",
    ),
    (
        "Rock Steady 94 Country",
        "http://streamingcenter.radiohosting.live:1830/stream",
        "Global",
        "Country",
    ),
];
