// This file is automatically generated by scripts/check_radios.py
pub const DEFAULT_RADIOS: &[(&str, &str, &str, &str)] = &[
    ("Antenne Bayern", "http://stream.antenne.de/antenne", "Germany", "Pop, Top 40"),
    ("Cubic Space Radio", "http://music.cubicspace.fm:42424/mpeg", "UK", "Electronic, Ambient"),
    ("Da Hub Radio", "https://stream.dahubradio.co.uk:8848/stream", "UK", "Urban, Hip-Hop"),
    ("FIP", "https://stream.radiofrance.fr/fip/fip_hifi.m3u8?id=radiofrance", "France", "Eclectic, Jazz, Rock"),
    ("Jazz & Blues Radio", "https://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3", "Switzerland", "Jazz, Blues"),
    ("KEXP", "https://kexp-mp3-128.streamguys1.com/kexp128.mp3", "USA", "Alternative, Indie"),
    ("KissFM", "http://online.kissfm.ua/KissFM", "Ukraine", "Electronic, Dance"),
    ("NTS Radio 1", "https://stream-relay-geo.ntslive.net/stream", "UK", "Underground, Electronic"),
    ("Nature Radio", "https://nature-rex.radioca.st/stream", "Global", "Nature, Relax"),
    ("Paddygrooves", "https://a12.siar.us/radio/8230/radio.mp3", "India", "Bollywood, Pop"),
    ("Radio Paradise (Main)", "http://stream.radioparadise.com/mp3-128", "USA", "Rock, Alternative"),
    ("Radio Regional Portugal", "http://193.70.40.92:8000/stream/2/", "Portugal", "Local, News"),
    ("SomaFM Drone Zone", "http://ice1.somafm.com/dronezone-128-mp3", "Global", "Ambient, Drone"),
    ("SomaFM Groove Salad", "http://ice1.somafm.com/groovesalad-128-mp3", "Global", "Chillout, Ambient"),
];
