// This file is automatically generated by scripts/check_radios.py
pub const DEFAULT_RADIOS: &[(&str, &str, &str, &str)] = &[
    (
        "Antenne Bayern",
        "http://stream.antenne.de/antenne",
        "Germany",
        "Pop, Top 40",
    ),
    (
        "Cubic Space Radio",
        "http://music.cubicspace.fm:42424/mpeg",
        "UK",
        "Electronic, Ambient",
    ),
    (
        "Da Hub Radio",
        "https://stream.dahubradio.co.uk:8848/stream",
        "UK",
        "Urban, Hip-Hop",
    ),
    (
        "FIP",
        "https://stream.radiofrance.fr/fip/fip_hifi.m3u8?id=radiofrance",
        "France",
        "Eclectic, Jazz, Rock",
    ),
    (
        "Jazz & Blues Radio",
        "https://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3",
        "Switzerland",
        "Jazz, Blues",
    ),
    (
        "KEXP",
        "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
        "USA",
        "Alternative, Indie",
    ),
    (
        "KissFM",
        "http://online.kissfm.ua/KissFM",
        "Ukraine",
        "Electronic, Dance",
    ),
    (
        "NTS Radio 1",
        "https://stream-relay-geo.ntslive.net/stream",
        "UK",
        "Underground, Electronic",
    ),
    (
        "Nature Radio",
        "https://nature-rex.radioca.st/stream",
        "Global",
        "Nature, Relax",
    ),
    (
        "Paddygrooves",
        "https://a12.siar.us/radio/8230/radio.mp3",
        "India",
        "Bollywood, Pop",
    ),
    (
        "Radio Paradise (Main)",
        "http://stream.radioparadise.com/mp3-128",
        "USA",
        "Rock, Alternative",
    ),
    (
        "SomaFM Drone Zone",
        "http://ice1.somafm.com/dronezone-128-mp3",
        "Global",
        "Ambient, Drone",
    ),
    (
        "SomaFM Groove Salad",
        "http://ice1.somafm.com/groovesalad-128-mp3",
        "Global",
        "Chillout, Ambient",
    ),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_radio_stations_not_empty() {
        assert!(!DEFAULT_RADIOS.is_empty());
    }

    #[test]
    fn test_radio_stations_valid_fields() {
        for (name, url, country, tags) in DEFAULT_RADIOS {
            assert!(!name.is_empty(), "Station name should not be empty");
            assert!(!url.is_empty(), "Station URL should not be empty for {}", name);
            assert!(!country.is_empty(), "Station country should not be empty for {}", name);
            assert!(!tags.is_empty(), "Station tags should not be empty for {}", name);
        }
    }

    #[test]
    fn test_radio_stations_url_format() {
        for (name, url, _, _) in DEFAULT_RADIOS {
            assert!(
                url.starts_with("http://") || url.starts_with("https://"),
                "URL for {} must start with http:// or https://, found: {}",
                name,
                url
            );
        }
    }

    #[test]
    fn test_radio_stations_unique_names() {
        let mut names = std::collections::HashSet::new();
        for (name, _, _, _) in DEFAULT_RADIOS {
            assert!(names.insert(name), "Duplicate station name found: {}", name);
        }
    }

    #[test]
    fn test_radio_stations_unique_urls() {
        let mut urls = std::collections::HashSet::new();
        for (_, url, _, _) in DEFAULT_RADIOS {
            assert!(urls.insert(url), "Duplicate station URL found: {}", url);
        }
    }

    #[test]
    fn test_radio_stations_tags_format() {
        for (name, _, _, tags) in DEFAULT_RADIOS {
            assert!(tags.contains(", ") || !tags.is_empty(), "Tags for {} should be comma-separated or non-empty", name);
        }
    }
}
