#!/usr/bin/env python3
import requests
import concurrent.futures
from pathlib import Path

# Default radios from src/core/radio_stations.rs
# Format: (name, url, country, tags)
DEFAULT_RADIOS = [
    ("SomaFM Groove Salad", "http://ice1.somafm.com/groovesalad-128-mp3", "Global", "Chillout, Ambient"),
    ("SomaFM Drone Zone", "http://ice1.somafm.com/dronezone-128-mp3", "Global", "Ambient, Drone"),
    ("FIP", "https://stream.radiofrance.fr/fip/fip_hifi.m3u8?id=radiofrance", "France", "Eclectic, Jazz, Rock"),
    ("Radio Paradise (Main)", "http://stream.radioparadise.com/mp3-128", "USA", "Rock, Alternative"),
    ("KEXP", "https://kexp-mp3-128.streamguys1.com/kexp128.mp3", "USA", "Alternative, Indie"),
    ("NTS Radio 1", "https://stream-relay-geo.ntslive.net/stream", "UK", "Underground, Electronic"),
    ("Antenne Bayern", "http://stream.antenne.de/antenne", "Germany", "Pop, Top 40"),
    ("Jazz24", "https://live.jazz24.org/jazz24-mp3", "USA", "Jazz"),
    ("Cinemix", "http://94.23.252.14:8067/live", "France", "Soundtracks, Instrumental"),
    ("Swiss Groove", "https://icecast.argon.ch/swissgroove", "Switzerland", "Groove, Jazz, Funk"),
    ("Radio 105", "http://shoutcast.radio105.it:8000/105.mp3", "Italy", "Pop, Dance"),
    ("KissFM", "http://online.kissfm.ua/KissFM", "Ukraine", "Electronic, Dance"),
    ("Paddygrooves", "https://a12.siar.us/radio/8230/radio.mp3", "India", "Bollywood, Pop"),
    ("Jazz & Blues Radio", "https://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3", "Switzerland", "Jazz, Blues"),
    ("Nature Radio", "https://nature-rex.radioca.st/stream", "Global", "Nature, Relax"),
    ("FreeCodeCamp Radio", "https://stream.freecodecamp.org/radio.mp3", "Global", "Chillhop, Lo-Fi"),
    ("Cubic Space Radio", "http://music.cubicspace.fm:42424/mpeg", "UK", "Electronic, Ambient"),
    ("Radio Regional Portugal", "http://193.70.40.92:8000/stream/2/", "Portugal", "Local, News"),
    ("Da Hub Radio", "https://stream.dahubradio.co.uk:8848/stream", "UK", "Urban, Hip-Hop"),
]

def check_station(station):
    name, url, country, tags = station
    try:
        # Use a short timeout and stream=True to avoid downloading the whole stream
        response = requests.get(url, timeout=5, stream=True, headers={'User-Agent': 'Chord/HealthCheck'})
        if response.status_code == 200:
            print(f"[OK] {name}")
            return station
        else:
            print(f"[FAILED] {name} (Status: {response.status_code})")
            return None
    except Exception as e:
        print(f"[ERROR] {name} ({str(e)})")
        return None

def write_radio_stations(stations):
    output_path = Path("src/core/radio_stations.rs")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w") as f:
        f.write("// This file is automatically generated by scripts/check_radios.py\n")
        f.write("pub const DEFAULT_RADIOS: &[(&str, &str, &str, &str)] = &[\n")
        for name, url, country, tags in stations:
            # Escape quotes in strings
            safe_name = name.replace('"', '\\"')
            safe_url = url.replace('"', '\\"')
            safe_country = country.replace('"', '\\"')
            safe_tags = tags.replace('"', '\\"')
            f.write(f'    ("{safe_name}", "{safe_url}", "{safe_country}", "{safe_tags}"),\n')
        f.write("];\n")
    print(f"\nSuccessfully wrote {len(stations)} stations to {output_path}")

def main():
    print(f"Checking {len(DEFAULT_RADIOS)} radio stations...")
    valid_stations = []
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(check_station, s) for s in DEFAULT_RADIOS]
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result:
                valid_stations.append(result)
    
    if valid_stations:
        # Sort by name for consistency
        valid_stations.sort(key=lambda x: x[0])
        write_radio_stations(valid_stations)
    else:
        print("No valid stations found. Skipping file update.")

if __name__ == "__main__":
    main()
